hauntedmap/urls.py
from django.conf.urls import patterns, include, url



from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url('', include('website.urls')),
    url(r'^external_data/', include('external_data.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^facebook/', include('django_facebook.urls')),
    url(r'^accounts/', include('django_facebook.auth_urls')), #Don't add this line if you use django registration or userena for registration and auth.


)

website/urls.py
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView

__author__ = 'derya'

from django.conf.urls import patterns, url
from django.template.defaultfilters import register
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.views.decorators.cache import cache_page

from views import Index, HauntedLocationSearch, HauntedLocationDetail, AboutUs, HowItWorks, TestView, HauntedEpisodeGuide
from models import Newsletter, Comment

urlpatterns = patterns('',


    url(r'^$', cache_page(60 * 1)(Index.as_view()), name="HauntedIndex"),
    url(r'^detail/(?P<slug>[-\w\d]+),(?P<pk>\d+)$', cache_page(60 * 1)(HauntedLocationDetail.as_view()), name='HauntedLocationDetail'),
    url(r'^about_us$',AboutUs.as_view(), name='AboutUs'),
    url(r'^how_it_works$',HowItWorks.as_view(), name='HowItWorks'),
    url(r'^test$',TestView.as_view(), name='test'),
    url(r'^episode_guide',cache_page(60 * 1)(HauntedEpisodeGuide.as_view()), name='HauntedEpisodeGuide'),
    #GET Form returns
    url(r'^search$',HauntedLocationSearch.as_view(), name='HauntedLocationSearch'),
    #POST Form returns
    url(r'^newsletter$',require_POST(CreateView.as_view(model=Newsletter, success_url="/website/", template_name="website/partial/_dummy.html")), name='NewsletterView' ),
    url(r'^comment$',CreateView.as_view(model=Comment, success_url="/website/",template_name="website/partial/_dummy.html"), name='CommentView' ),


)

website/models.py
from django.template.defaultfilters import slugify

# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models
class Country(models.Model):
    def __unicode__(self):
        return self.country_name
    country_name = models.CharField(max_length=255)

class State(models.Model):
    def __unicode__(self):
        return self.state_name
    state_name = models.CharField(max_length=255)
    country = models.ForeignKey(Country)

class Category(models.Model):
    def __unicode__(self):
        return self.category_name
    category_name = models.CharField(max_length=255)
    presentation_name = models.CharField(max_length=255)

class  HauntedLocation(models.Model):
    def __unicode__(self):
        return self.name

    def _url(self):
        super(HauntedLocation, self).save()

        url = '%s,%s' % (
             slugify(self.name),slugify(self.id)
        )
        return url
    slug = property(_url)


    @models.permalink
    def get_absolute_url(self):
        return ('HauntedLocationDetail', (slugify(self.name), slugify(self.id)))

    name = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    category = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    geom = models.MultiPointField(srid=4326)
    objects = models.GeoManager()

class HauntedLocationDescription(models.Model):
    def __unicode__(self):
        return self.html_content
    haunted_location = models.ForeignKey(HauntedLocation, unique=True)
    html_content = models.TextField()

class HauntedLocationMetaData(models.Model):
    haunted_location = models.ForeignKey(HauntedLocation, unique=True)
    category = models.ForeignKey(Category, unique=True)
    description = models.ForeignKey(HauntedLocationDescription, unique=True)
    country = models.ForeignKey(Country, unique=True)
    state = models.ForeignKey(State, unique=True)

class TvShow(models.Model):
    def __unicode__(self):
        return self.name
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    tvdb_id = models.IntegerField(blank=True)
    imdb_id = models.CharField(max_length=255, blank=True)
    zap2it_id = models.CharField(max_length=255, blank=True)

class Newsletter(models.Model):
    def __unicode__(self):
        return self.email
    email = models.EmailField()
    status = models.BinaryField(default=bin(1))


class Comment(models.Model):
    def __unicode__(self):
        return self.email
    comment = models.TextField()
    status = models.BinaryField(default=bin(0), blank=True, null=True)
    user_name = models.CharField(default="", max_length=255, blank=True, null=True)
    email = models.EmailField(default="", blank=True, null=True)
    haunted_location = models.ForeignKey(HauntedLocation)

# Auto-generated `LayerMapping` dictionary for  --srid=4326 model
HauntedLocation_mapping = {
    'id':'id',
    'name' : 'name',
    'latitude' : 'latitude',
    'longitude' : 'longitude',
    'category' : 'category',
    'geom' : 'MULTIPOINT',
}


# Create your models here.

website/forms.py
__author__ = 'derya'
# forms.py
from django import forms
from models import Newsletter

class NewsletterForm(forms.Form):
    email = forms.CharField()

    def save_email(self):
        Newsletter.email = ''

website/views.py
from urllib2 import urlopen
from xml.dom import minidom
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django.template.defaultfilters import slugify, register


import json


from django.http import HttpResponse, Http404


from models import HauntedLocation, HauntedLocationDescription, TvShow




class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return HttpResponse(
            self.convert_context_to_json(context),
            content_type='application/json',
            **response_kwargs
        )

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return json.dumps(context)


class Index(View):
    template_name = 'website/index.html'
    def get(self,request):

        haunted_location_list = HauntedLocation.objects.all()


        context = {'haunted_location_list': haunted_location_list}

        return render(request, self.template_name, context)

class AboutUs(TemplateView):
    template_name = 'website/about_us.html'

class HowItWorks(TemplateView):
    template_name = 'website/how_it_works.html'


class HauntedLocationSearch(ListView):
    template_name = 'website/hauntedlocation_search.html'
    context_object_name = 'haunted_location_list'

    model = HauntedLocation

    # def post(self, request, *args, **kwargs):
    #     context ={'results':"1"}
    #     if(request.POST["query"]):
    #         query = request.POST["query"]
    #         print request.POST["query"]
    #         haunted_location_list = HauntedLocation.objects.filter(name__icontains=query)
    #         context ={'results': haunted_location_list}
    #     print context
    #     return HttpResponse(context)
    #
    #
    # def get(self, request, *args, **kwargs):
    #     return render(request,self.template_name,self.context)

    def get_queryset(self):
        if self.request.REQUEST.get("query"):
            self.query = self.request.REQUEST.get("query");
            self.search_obj = HauntedLocation.objects.filter(name__icontains=self.query)
        return HauntedLocation.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(HauntedLocationSearch, self).get_context_data(**kwargs)
        # Add in the publisher
        if hasattr(self, 'query'):
            context['search_results'] = self.search_obj

        return context




class HauntedLocationDetail(DetailView):
    model = HauntedLocation
    context_object_name = 'haunted_location'


    def get_object(self, queryset=None):
        obj = super(HauntedLocationDetail, self).get_object(queryset)
        self.wikipedia_name = obj.name
        try:
            self.description = get_object_or_404(HauntedLocationDescription, haunted_location = obj.id)
        except Http404:
            self.description = "Not Found"
        return obj

    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super(HauntedLocationDetail, self).get_context_data(**kwargs)
        # Add in HTML content
        context['haunted_location_description'] = self.description
        context['haunted_location_youtube_name'] = slugify(self.wikipedia_name)
        context['haunted_location_wikipedia_name'] = self.wikipedia_name.replace(" ","_").replace("'","%27")

        return context






class TestView(TemplateView):
    template_name = 'website/test.html'

class HauntedEpisodeGuide(ListView):
    model = TvShow
    template_name = 'website/episode_guide.html'
    context_object_name = 'tvshows'

    TVDB_API_KEY = '9036B99877C335CD'
    url_base = 'http://thetvdb.com/api/'
    url = url_base +TVDB_API_KEY+'/series/125391/all/'



    def get_queryset(self):
        if self.request.REQUEST.get("id"):
            self.query_id = self.request.REQUEST.get("id");
            try:
                search_obj = get_object_or_404(TvShow, id=self.query_id)
                self.tvdb_id = str(search_obj.tvdb_id)
            except Http404:
                self.tvdb_id = None
        return TvShow.objects.all()

    def get_context_data(self, **kwargs):
        #Calling the base implementation for context
        context = super(HauntedEpisodeGuide, self).get_context_data(**kwargs)
        # Get Episodes Return
        try:
            context['episodes_list'] = self.get_episodes(self.tvdb_id)
        except Exception as e:
            print 'episode server problem' + str(e)
        if self.request.REQUEST.get("id"):
            try:
                context['query_id'] = int(self.query_id)
                print self.query_id
            except:
                print 'no query selected'
        return context

    def get_episodes(self,series_id):
        episodes_list = []


        self.url = self.url_base + self.TVDB_API_KEY+'/series/'+series_id+'/all/'
        xml_doc = urlopen(self.url)
        parsed_xml = minidom.parse(xml_doc)
        episodes = parsed_xml.getElementsByTagName("Episode")
        for episode in episodes:
            episode_dict = {}
            episode_name = episode.getElementsByTagName("EpisodeName")[0].firstChild.data
            episode_id = episode.getElementsByTagName("id")[0].firstChild.data
            episode_number = episode.getElementsByTagName("EpisodeNumber")[0].firstChild.data
            season_number = episode.getElementsByTagName("SeasonNumber")[0].firstChild.data
            language = episode.getElementsByTagName("Language")[0].firstChild.data
            try:
                overview = episode.getElementsByTagName("Overview")[0].firstChild.data
            except:
                overview =''
            episode_dict = dict(episode_name=episode_name,episode_id=episode_id, episode_number=episode_number, season_number=season_number,language=language, overview=overview)
            episodes_list.append(episode_dict)
        return episodes_list

website/templates/website/_index-script.html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
{% load staticfiles %}
<script src="{{ STATIC_URL }}website/javascript/jquery.ba-outside-events.js"> </script>

<script>


    var map;
    var pointsLayer;

    function mapInit(){
        var lon = 0;
        var lat = 0;
        var zoom = 3;

        map = new OpenLayers.Map("mapp", {
            units : 'm',
            id:'haunted_map'
        });


        var gsat = new OpenLayers.Layer.Google(
                "Google Satellite",
                {type: google.maps.MapTypeId.SATELLITE, numZoomLevels: 22, sphericalMercator: true}
        );

        var gphy = new OpenLayers.Layer.Google(
                "Google Physical",
                {type: google.maps.MapTypeId.TERRAIN, sphericalMercator: true}
                // used to be {type: G_PHYSICAL_MAP}
        );
        var gmap = new OpenLayers.Layer.Google(
                "Google Streets", // the default
                {numZoomLevels: 20, sphericalMercator: true}
                // default type, no change needed here
        );
        var ghyb = new OpenLayers.Layer.Google(
                "Google Hybrid",
                {type: google.maps.MapTypeId.HYBRID, numZoomLevels: 20, sphericalMercator: true}
                // used to be {type: G_HYBRID_MAP, numZoomLevels: 20}
        );
        arrayOSM = ["http://otile1.mqcdn.com/tiles/1.0.0/map/${z}/${x}/${y}.jpg",
            "http://otile2.mqcdn.com/tiles/1.0.0/map/${z}/${x}/${y}.jpg",
            "http://otile3.mqcdn.com/tiles/1.0.0/map/${z}/${x}/${y}.jpg",
            "http://otile4.mqcdn.com/tiles/1.0.0/map/${z}/${x}/${y}.jpg"];
        arrayAerial = ["http://otile1.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.jpg",
            "http://otile2.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.jpg",
            "http://otile3.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.jpg",
            "http://otile4.mqcdn.com/tiles/1.0.0/sat/${z}/${x}/${y}.jpg"];

        baseOSM = new OpenLayers.Layer.OSM("MapQuest-OSM Tiles", arrayOSM);
        baseAerial = new OpenLayers.Layer.OSM("MapQuest Open Aerial Tiles", arrayAerial);

        map.addLayer(baseOSM);
        map.addLayer(baseAerial);


        map.addLayer(gsat);
        map.addLayer(gphy);
        map.addLayer(gmap);
        map.addLayer(ghyb);

        var switcherControl = new OpenLayers.Control.LayerSwitcher();
        map.addControl(switcherControl);
        switcherControl.maximizeControl();

        if (!map.getCenter()) {
            var lonLat = new OpenLayers.LonLat(lon, lat).transform(new OpenLayers.Projection("EPSG:4326"), map
                    .getProjectionObject());
            map.setCenter(lonLat, zoom);
        }



        {% if haunted_location_list %}
            featuresArray = new Array();
            {% for haunted_location in haunted_location_list %}

                var tempFeature = new OpenLayers.Feature.Vector(new OpenLayers.Geometry.Point({{ haunted_location.longitude }}, {{ haunted_location.latitude }}).transform(new OpenLayers.Projection("EPSG:4326"), map
                        .getProjectionObject()),{category:'{{haunted_location.category}}', slug:'{{haunted_location.get_absolute_url}}', name:'{{ haunted_location.name }}', id:'{{ haunted_location.id }}', lat:'{{ haunted_location.latitude }}', lon:'{{ haunted_location.longitude }}'});

                featuresArray.push(tempFeature);
            {% endfor %}
        {% else %}
        {% endif %}

        // create the layer styleMap by giving the default style a context
        var colors = ["red", "green", "blue"];
        var context = {

            getIcon: function(feature) {
                return feature.attributes["category"] === "Cemeteries" ? '{{ STATIC_URL }}website/icons/religious/cemetary.png':
                        feature.attributes["category"] === "Bridges" ?  '{{ STATIC_URL }}website/icons/monuments/bridge_old.png':
                                feature.attributes["category"] === "Ghost Lights" ?  '{{ STATIC_URL }}website/icons/tourism/star_3.png':
                                        feature.attributes["category"] === "Ghost Towns" ?  '{{ STATIC_URL }}website/icons/tourism/historicalquarter.png':
                                                feature.attributes["category"] === "Gravity Hills" ?  '{{ STATIC_URL }}website/icons/tourism/sight_2.png':
                                                        feature.attributes["category"] === "Historical Buildings" ?  '{{ STATIC_URL }}website/icons/tourism/bigcity.png':
                                                                feature.attributes["category"] === "Hotels and Inns" ?  '{{ STATIC_URL }}website/icons/hotels/bed_breakfast1-2.png':
                                                                        feature.attributes["category"] === "Lighthouses" ?  '{{ STATIC_URL }}website/icons/tourism/lighthouse-2.png':
                                                                                feature.attributes["category"] === "Military" ?  '{{ STATIC_URL }}website/icons/defensive/castle-2.png':
                                                                                        feature.attributes["category"] === "Miscellaneous" ?  '{{ STATIC_URL }}website/icons/ghost/ghost_of_hunger_past.png':
                                                                                                feature.attributes["category"] === "Houses Of Worship" ?  '{{ STATIC_URL }}website/icons/religious/prayer.png':
                                                                                                        feature.attributes["category"] === "Historical Sites" ?  '{{ STATIC_URL }}website/icons/tourism/historicalquarter.png':
                                                                                                                '{{ STATIC_URL }}website/icons/ghost/ghost_of_hunger_past.png';

            }
        };
        var defaultTemplate = {
            externalGraphic: "${getIcon}", // using context.getSize(feature)
            'pointRadius': 15
        };

        var selectTemplate = {
            externalGraphic: "${getIcon}", // using context.getSize(feature)
            'pointRadius': 30
        }

        var defaultStyle = new OpenLayers.Style(defaultTemplate, {context: context});
        var selectStyle = new OpenLayers.Style(selectTemplate, {context: context});
        pointsLayer = new OpenLayers.Layer.Vector("Haunted Locations",{
            styleMap: new OpenLayers.StyleMap({default: defaultStyle, select:selectStyle}),
            rendererOptions: {zIndexing: true},
            eventListeners:{
                'featureselected':function(evt){
                    var feature = evt.feature;
                    var popup = new OpenLayers.Popup.FramedCloud("popup",
                            OpenLayers.LonLat.fromString(feature.geometry.toShortString()),
                            null,
                            feature.attributes.category+"<br>"+feature.attributes.name,
                            null,
                            true,
                            null
                    );
                    popup.autoSize = true;
                    popup.maxSize = new OpenLayers.Size(400,800);
                    popup.fixedRelativePosition = true;
                    feature.popup = popup;
                    map.addPopup(popup);
                },
                'featureunselected':function(evt){
                    var feature = evt.feature;
                    map.removePopup(feature.popup);
                    feature.popup.destroy();
                    feature.popup = null;
                },
                'featureclick':function(evt){
                    var feature = evt.feature;
                    map.removePopup(feature.popup);
                    feature.popup.destroy();
                    feature.popup = null;
                    var popup_id = "big_popup";
                    {% load staticfiles %}
                    var html_content = "Category:"+feature.attributes.category+"<br>"+"Link:"+"<a href="+ feature.attributes.slug+"> "+feature.attributes.name+"</a>"+"<br>"+'<img src="{% static "website/icons/ghost/ghost.png" %}" alt="My image"/>';
                    var popup = new OpenLayers.Popup.FramedCloud(popup_id,
                            OpenLayers.LonLat.fromString(feature.geometry.toShortString()),
                            null,
                            html_content,
                            null,
                            true,
                            null
                    );
                    popup.autoSize = true;
                    popup.maxSize = new OpenLayers.Size(400,800);
                    popup.fixedRelativePosition = true;
                    map.addPopup(popup);
                }
            }
        });
        pointsLayer.addFeatures(featuresArray);

        map.addLayer(pointsLayer);

        // Create a select feature control and add it to the map.
        var select = new OpenLayers.Control.SelectFeature(pointsLayer, {hover: true});
        map.addControl(select);
        select.activate();


        function doFocusLocation(obj){

            var id = obj.getAttribute("data_id");
            var feature = pointsLayer.getFeaturesByAttribute("id",id);
            var lon = feature.lon;
            var lat = feature.lat;
            map.setCenter()
            alert(feature.attributes.id);
            {% comment %}   map.setCenter(10,10,5);{% endcomment %}

            return false;
        }
        $( document ).ready(function() {
            $('#search_results').bind('clickoutside', function (event) {

                $('#search_results').removeClass('search_results_active');
                $('#search_results').addClass('search_results_inactive');

            });
        });




    }

</script>

website/templates/website/about_us.html
{% extends "website/base.html" %}

website/templates/website/episode_guide.html
{% extends "website/base.html" %}
{% block content %}
    <div class="container">
        <form name="myform" method="GET">
            <div align="center">
                <select name="id">
                    {% for tvshow in tvshows %}
                        {% if query_id == tvshow.id %}
                            <option value="{{ tvshow.id }}" selected>{{ tvshow.name }}</option>
                        {% else %}
                            {{ query_id }}
                            {{ tvshow.id }}
                            <option value="{{ tvshow.id }}">{{ tvshow.name }}</option>
                        {% endif %}

                    {% endfor %}
                </select>
                <input type="submit" value="Search">
            </div>
        </form>
        {% if episodes_list %}
            <table class="table">
                <tr>
                    <th>Episode Name</th>
                    <th>Episode Number</th>
                    <th>Season</th>
                    <th>Summary</th>
                </tr>

                {% for episode in episodes_list %}
                    <tr>
                        <td>{{ episode.episode_name }}</td>
                        <td>{{ episode.episode_number }}</td>
                        <td>{{ episode.season_number }}</td>
                        <td>{{ episode.overview }}</td>
                    </tr>
                {% endfor %}
            </table>
        {%  endif %}
    </div>
{% endblock %}

website/templates/website/hauntedlocation_detail.html
{% extends "website/base.html" %}

{% block content %}
    <div class="container">
        <h2>Haunted Spot Details</h2>
        <div id="map" style="width:800px; height:300px;"></div>
        {{ haunted_location.name }}<br>


        Latitude: {{ haunted_location.latitude }} <br>
        Longitude: {{ haunted_location.longitude }} <br>
        <div id='address'></div>
        <p><h1>Wikipedia Entry</h1></p>
        <div id='wikipedia'></div>
        <div id ='wikipedia_url'></div>

        <p><h1>YouTube Videos</h1></p>
        {%  include 'website/partial/_youtube_search.html' %}

        <div class="col-md-6 md-margin-bottom-40">
            <!-- Monthly Newsletter -->
<!--            <div class="headline"><h2>Please Leave Comment</h2></div>
            <form action="{% url 'CommentView' %}" method="post" class="footer-subsribe" id="comment_form">{% csrf_token %}
                <div class="input-group">
                    <input type="text" maxlength="255" name="user_name" class="form-control" placeholder="User Name (Optional)" id="id_user_name">
                    <input type="text" maxlength="255" name="email" class="form-control" placeholder="Email Address (Optional)" id="id_email">
                    <input type="hidden" name="haunted_location" value="{{haunted_location.id}}">
                    <textarea class="form-control" rows="4" name="comment" id = "id_comment"></textarea>
                    {#                        <label for="id_email">Email:</label> <input id="id_email" class="form-control" maxlength="255" name="email" type="text" />#}
                        <span class="input-group-btn">
                            <button class="btn-u" type="submit">Subscribe</button>
                        </span>
                </div>&lt;!&ndash; /input-group &ndash;&gt;
            </form>-->
        </div>
    </div>
{% endblock %}

{% block scripts %}


    <script src="http://www.mapquestapi.com/sdk/js/v7.0.s/mqa.toolkit.js?key=Fmjtd%7Cluur296rnh%2C2a%3Do5-90rsdw"></script>

    <script type="text/javascript">

        /*An example of using the MQA.EventUtil to hook into the window load event and execute defined function
         passed in as the last parameter. You could alternatively create a plain function here and have it
         executed whenever you like (e.g. <body onload="yourfunction">).*/

        MQA.EventUtil.observe(window, 'load', function() {

            /*Create an object for options*/
            var mapOptions={
                elt:document.getElementById('map'),        /*ID of element on the page where you want the map added*/
                zoom:20,                                   /*initial zoom level of map*/
                latLng:{lat:{{ haunted_location.latitude }}, lng:{{ haunted_location.longitude }}},   /*center of map in latitude/longitude*/
                mtype:'map'                                /*map type (map)*/
            };

            /*Construct an instance of MQA.TileMap with the options object*/
            window.map = new MQA.TileMap(mapOptions);

            MQA.withModule('largezoom','traffictoggle','viewoptions','geolocationcontrol','insetmapcontrol','mousewheel', function() {

                map.addControl(
                        new MQA.LargeZoom(),
                        new MQA.MapCornerPlacement(MQA.MapCorner.TOP_LEFT, new MQA.Size(5,5))
                );

                map.addControl(new MQA.TrafficToggle());

                map.addControl(new MQA.ViewOptions());

                map.addControl(
                        new MQA.GeolocationControl(),
                        new MQA.MapCornerPlacement(MQA.MapCorner.TOP_RIGHT, new MQA.Size(10,50))
                );

                /*Inset Map Control options */
                var controlOptions={
                    size:{width:150, height:125},
                    zoom:15,
                    mapType:'map',
                    minimized: true
                };

                map.addControl(
                        new MQA.InsetMapControl(controlOptions),
                        new MQA.MapCornerPlacement(MQA.MapCorner.BOTTOM_RIGHT)
                );

                map.enableMouseWheelZoom();

                MQA.withModule('geocoder', function() {
                    /*Executes a geocode with an object containing lat/lng properties, adds result to the map, and
                     adds a function to be called once geocoding is complete.*/
                    map.reverseGeocodeAndAddLocation(
                            {lat:{{ haunted_location.latitude }}, lng:{{ haunted_location.longitude }}}, showAddress
                    );

                    /*Example function used to show the address of the geocoded location*/
                    function showAddress(data) {
                        var html = '';
                        var response = data.results[0].locations[0];

                        html = '<p><b>ADDRESS: </b>';
                        html += response.street + ', ';
                        html += response.adminArea5 + ', ' + response.adminArea3 + ' ' + response.postalCode + '</p>';
                        html += '<p><b>COUNTRY:</b>'
                        html += response.adminArea1+'<br>';
                        html += '<p><b>STATE:</b>'
                        html += response.adminArea3+'<br>'
                        document.getElementById('address').innerHTML = html;
                        map.setZoomLevel(15);
                    }

                });





            });
        });


    </script >

    <script type="text/javascript">
        var url = "http://en.wikipedia.org/w/api.php?action=parse&page={{ haunted_location_wikipedia_name }}&format=json&prop=text&section=0";


        $.ajax({
            type: 'GET',
            url: url,
            async: false,
            jsonpCallback: 'jsonCallback',
            contentType: "application/json",
            dataType: 'jsonp',
            success: function(json) {
                if (typeof json.error == "undefined"){
                    var html = '<p><b>'+json.parse.title +'</b>' ;
                    html += json.parse.text["*"]+'</p>';
                    document.getElementById('wikipedia').innerHTML=html;
                    item = document.getElementById('wikipedia');
                    $('#wikipedia a').contents().unwrap();
                    $('#wikipedia sup').remove();
                    $('#wikipedia table').remove();
                    $('#wikipedia .thumb').remove();
                    $('#wikipedia .error').hide();

                }


                contentHtml =  "<p>"+"<a href="+"http://en.wikipedia.org/wiki/{{ haunted_location_wikipedia_name }}"+">"+ "Original Wikipedia Article"+"</a>";
                document.getElementById('wikipedia_url').innerHTML = contentHtml;

            },
            error: function(e) {
                alert(e.message);
            }
        });




    </script>
{% endblock %}

website/templates/website/hauntedlocation_list.html
{% extends "website/base.html" %}

{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

website/templates/website/hauntedlocation_search.html
    <h2>Search Results</h2>
    {% for search_result in search_results %}
        <li><a href="#" data_id ="{{ search_result.id }}" onclick="doFocusLocation(this); return false;"> {{ search_result.name }}</a></li>
    {% endfor %}

website/templates/website/how_it_works.html
{% extends "website/base.html" %}